import { useEffect, useState } from 'react';
import { ArrowRight, LoaderCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { listPublicNews } from '@/lib/adminApi';
import type { NewsRecord } from '@/types/admin';

export default function NewsPage() {
  const [articles, setArticles] = useState<NewsRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void listPublicNews().then(setArticles).catch(() => setError('Berita belum dapat dimuat.')).finally(() => setLoading(false)); }, []);
  return <section className="min-h-screen bg-[#fffaf3] px-4 pb-20 pt-32 text-[#241811] sm:px-6 sm:pt-40"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.26em] text-orange-600">Visitiga Journal</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Berita <span className="text-orange-500">terbaru.</span></h1><p className="mt-4 max-w-2xl text-[#735c4d]">Artikel dan kabar terbaru dari Visitiga Media.</p>{loading ? <div className="mt-16 text-slate-500"><LoaderCircle className="mr-2 inline h-4 w-4 animate-spin" />Memuat berita…</div> : error ? <p className="mt-16 text-red-600">{error}</p> : articles.length === 0 ? <p className="mt-16 text-[#735c4d]">Belum ada berita yang dipublikasikan.</p> : <div className="mt-12 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{articles.map((article) => <article key={article.id} className="overflow-hidden rounded-2xl border border-[#ead5c1] bg-white shadow-sm"><img src={article.cover_image} alt="" className="aspect-[16/9] w-full object-cover" /><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-600">{article.category}</p><h2 className="mt-3 text-2xl font-black leading-tight">{article.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#735c4d]">{article.excerpt}</p><p className="mt-5 text-xs text-[#735c4d]">{article.author} · {new Date(article.published_at!).toLocaleDateString('id-ID')}</p><Link to={`/news/${article.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-orange-600 hover:text-orange-700">Baca selengkapnya <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div>}</div></section>;
}
