-- One-time import of the content that originally lived in the React source.
-- Each row is protected by image URL so re-running this script will not duplicate it.
insert into public.portfolios (title, image_url, client, category, description)
select legacy.title, legacy.image_url, legacy.client, legacy.category, legacy.description
from (values
  ('Mall Pesona Square','/portfolio/indoor-1.jpg','Visitiga Media','Indoor Media',''),('Matahari Mall','/portfolio/indoor-2.jpg','Visitiga Media','Indoor Media',''),('Pascal 23','/portfolio/indoor-3.jpg','Visitiga Media','Indoor Media',''),('Event Dynamix','/portfolio/indoor-4.jpg','Visitiga Media','Indoor Media',''),('Bank BPD DIY','/portfolio/indoor-5.jpg','Visitiga Media','Indoor Media',''),('Bandara Soekarno Hatta Terminal 2','/portfolio/indoor-6.jpg','Visitiga Media','Indoor Media',''),('Gedung DPR MPR','/portfolio/indoor-7.jpg','Visitiga Media','Indoor Media',''),('Bank BPD DIY','/portfolio/indoor-8.jpg','Visitiga Media','Indoor Media',''),('Plaza Indonesia','/portfolio/indoor-9.jpg','Visitiga Media','Indoor Media',''),('LED VIDEOTRON P2.5 AL-Azhar','/portfolio/indoor-10.jpg','Visitiga Media','Indoor Media',''),('LED Videotron Indoor 2.5 Jambore','/portfolio/indoor-11.jpg','Visitiga Media','Indoor Media',''),('LED Videotron Indoor 2.5 Gedung Graha Dirgantara','/portfolio/indoor-12.jpg','Visitiga Media','Indoor Media',''),
  ('Metro Tanah Abang','/portfolio/outdoor/outdoor-1.jpg','Visitiga Media','Outdoor Media',''),('Main Gate Bandara Halim Perdana Kusuma','/portfolio/outdoor/outdoor-2.jpg','Visitiga Media','Outdoor Media',''),('Menara T Tower','/portfolio/outdoor/outdoor-3.jpg','Visitiga Media','Outdoor Media',''),('Pemerintahan Kabupaten Bojonegoro','/portfolio/outdoor/outdoor-4.jpg','Visitiga Media','Outdoor Media',''),('Totem Minitron Sampoerna','/portfolio/outdoor/outdoor-5.jpg','Visitiga Media','Outdoor Media',''),('Signature Park Pierre Tendean','/portfolio/outdoor/outdoor-6.jpg','Visitiga Media','Outdoor Media',''),('Bank BPD DIY Senopati','/portfolio/outdoor/outdoor-7.jpg','Visitiga Media','Outdoor Media',''),('Simpang Lima Semarang','/portfolio/outdoor/outdoor-8.jpg','Visitiga Media','Outdoor Media',''),('RS EMC Pekayon','/portfolio/outdoor/outdoor-9.jpg','Visitiga Media','Outdoor Media',''),('RS EMC Alam Sutera','/portfolio/outdoor/outdoor-10.jpg','Visitiga Media','Outdoor Media',''),('JPO depan Plaza Lawu Madiun','/portfolio/outdoor/outdoor-11.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P8 Simpang Lima Semarang','/portfolio/outdoor/outdoor-12.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P5 Outdoor Lombok Mandalika','/portfolio/outdoor/outdoor-13.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P6 Outdoor Lombok Mandalika','/portfolio/outdoor/outdoor-14.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P3.9 Outdoor Lombok Mandalika','/portfolio/outdoor/outdoor-15.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P3.9 Outdoor Lombok Mandalika','/portfolio/outdoor/outdoor-16.jpg','Visitiga Media','Outdoor Media',''),('LED Videotron P8 Outdoor Sanur Bali','/portfolio/outdoor/outdoor-17.jpg','Visitiga Media','Outdoor Media',''),
  ('Rental LED Event 1','/portfolio/rental/rental-1.png','Visitiga Media','Rental LED',''),('Event Nobar Videotron Madiun','/portfolio/rental/rental-2.jpg','Visitiga Media','Rental LED',''),('Event Ynot Games Vol 2','/portfolio/rental/rental-3.jpg','Visitiga Media','Rental LED',''),('Event Pupuk Kujang','/portfolio/rental/rental-4.jpg','Visitiga Media','Rental LED',''),('Wisuda UGM','/portfolio/rental/rental-5.jpg','Visitiga Media','Rental LED',''),('Indonesia International Motor Show Surabaya','/portfolio/rental/rental-6.jpg','Visitiga Media','Rental LED',''),('MOEHI SMA Muhamadiyah 1 Yogyakarta','/portfolio/rental/rental-7.jpg','Visitiga Media','Rental LED',''),('Event MotoGP Internasional 2025 Sirkuit Mandalika','/portfolio/rental/rental-8.jpg','Visitiga Media','Rental LED',''),('JCI National Convention Padma Hotel','/portfolio/rental/rental-9.jpg','Visitiga Media','Rental LED',''),('Budhi Hartono Sanjaja’s Birthday','/portfolio/rental/rental-10.jpg','Visitiga Media','Rental LED',''),('Marcell & Rere’s Wedding','/portfolio/rental/rental-11.jpg','Visitiga Media','Rental LED',''),('Indonesia Sport Summit 2025 GBK','/portfolio/rental/rental-12.jpg','Visitiga Media','Rental LED',''),
  ('Golo Convention Golomori, Labuan Bajo NTT','/portfolio/audiovisual/IMG_6406-scaled.jpg','Visitiga Media','Audio Visual',''),('Meeting Room Sarinah','/portfolio/audiovisual/IMG_9584-scaled.jpg','Visitiga Media','Audio Visual',''),('Paramount Petals','/portfolio/conventional/Billboard-Paramount-Petals.jpeg','Visitiga Media','Conventional Media',''),('Display Booth','/portfolio/conventional/Display-Booth.jpeg','Visitiga Media','Conventional Media',''),('Letter Sign Kuta Mandalika','/portfolio/conventional/Gambar-WhatsApp-2025-04-08-pukul-10.30.44_fca1b51d.jpg','Visitiga Media','Conventional Media',''),('Stasiun Railink Sudirman','/portfolio/conventional/Lightbox-Indoor-Railink-Sudirman.jpeg','Visitiga Media','Conventional Media',''),('Lightbox Outdoor','/portfolio/conventional/Lightbox-Outdoor.jpeg','Visitiga Media','Conventional Media',''),('Toko Taurus Braga','/portfolio/conventional/Shopsign-Toko-Taurus-Braga-Bandung.jpeg','Visitiga Media','Conventional Media','')
) as legacy(title, image_url, client, category, description)
where not exists (select 1 from public.portfolios p where p.image_url = legacy.image_url);

insert into public.news (title, cover_image, content, author, category, excerpt, published_at)
select legacy.title, legacy.cover_image, legacy.content, 'Visitiga Media', legacy.category, legacy.excerpt, legacy.published_at
from (values
  ('Kenapa Iklan Digital Jauh Lebih Efektif untuk Brand Anda?','/news/digital-advertising.jpg','Videotron membantu brand tampil lebih relevan, responsif, dan berkesan di ruang publik.','Digital Advertising','Videotron membantu brand tampil lebih relevan, responsif, dan berkesan di ruang publik.','2026-08-18'::date),
  ('Visitiga Media Raih Kepercayaan sebagai Mitra LED Utama MotoGP Mandalika 2025','/news/mandalika.png','Visitiga Media dipercaya menjadi mitra teknologi tampilan visual untuk MotoGP Mandalika 2025.','Event','Visitiga Media dipercaya menjadi mitra teknologi tampilan visual untuk MotoGP Mandalika 2025.','2026-08-12'::date),
  ('Digital Signage Bukan Sekadar Layar','/news/digital-signage.png','Digital signage menghubungkan tamu dengan layanan, pengalaman, dan citra merek secara real-time.','Hospitality','Digital signage menghubungkan tamu dengan layanan, pengalaman, dan citra merek secara real-time.','2026-08-05'::date),
  ('LED Indoor vs LED Outdoor: Kenapa Tidak Bisa Disamakan?','/news/led-indoor-vs-outdoor.jpeg','Kenali perbedaan kecerahan, ketahanan cuaca, dan pixel pitch sebelum memilih layar LED.','Technology','Kenali perbedaan kecerahan, ketahanan cuaca, dan pixel pitch sebelum memilih layar LED.','2026-07-29'::date),
  ('Bukan Sekadar Layar: Dampak Teknologi Visual terhadap Hospitality, Retail, Pendidikan, dan Pemerintahan','/news/technology-visual.jpg','Teknologi visual adalah pengungkit hasil untuk layanan, penjualan, pembelajaran, dan operasional.','Audio Visual','Teknologi visual adalah pengungkit hasil untuk layanan, penjualan, pembelajaran, dan operasional.','2026-07-23'::date)
) as legacy(title, cover_image, content, category, excerpt, published_at)
where not exists (select 1 from public.news n where n.cover_image = legacy.cover_image);
