-- Privacy-conscious, first-party client observability.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.website_observations (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('web_vital', 'client_error', 'csp_violation')),
  name text not null check (char_length(name) between 1 and 80),
  value double precision check (value is null or value between 0 and 600000),
  rating text check (rating is null or rating in ('good', 'needs-improvement', 'poor')),
  path text not null check (char_length(path) between 1 and 500 and path like '/%' and path not like '%?%'),
  fingerprint text not null check (char_length(fingerprint) between 8 and 128),
  release text not null default 'development' check (char_length(release) between 1 and 80),
  details jsonb not null default '{}'::jsonb check (octet_length(details::text) <= 4096),
  submission_hash text not null check (char_length(submission_hash) = 64),
  created_at timestamptz not null default now()
);

create index if not exists website_observations_created_at_idx on public.website_observations (created_at desc);
create index if not exists website_observations_kind_name_created_idx on public.website_observations (kind, name, created_at desc);
alter table public.website_observations enable row level security;

drop policy if exists "Admins view website observations" on public.website_observations;
create policy "Admins view website observations" on public.website_observations for select to authenticated using (public.is_admin());
revoke all on public.website_observations from anon, authenticated;
grant select on public.website_observations to authenticated;

create or replace function public.submit_website_observation(
  p_kind text, p_name text, p_value double precision, p_rating text, p_path text,
  p_fingerprint text, p_release text, p_details jsonb, p_submission_key uuid
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  submission_hash_value text := encode(extensions.digest(p_submission_key::text, 'sha256'), 'hex');
begin
  if p_kind not in ('web_vital', 'client_error', 'csp_violation')
    or char_length(trim(p_name)) not between 1 and 80
    or p_path !~ '^/[^?]{0,499}$'
    or char_length(trim(p_fingerprint)) not between 8 and 128
    or char_length(coalesce(trim(p_release), '')) not between 1 and 80
    or (p_value is not null and (p_value < 0 or p_value > 600000))
    or (p_rating is not null and p_rating not in ('good', 'needs-improvement', 'poor'))
    or octet_length(coalesce(p_details, '{}'::jsonb)::text) > 4096 then
    raise exception 'Invalid website observation';
  end if;

  if (select count(*) from public.website_observations where submission_hash = submission_hash_value and created_at > now() - interval '15 minutes') >= 60 then
    raise exception 'Observation rate limit exceeded';
  end if;

  if exists (select 1 from public.website_observations where submission_hash = submission_hash_value and fingerprint = trim(p_fingerprint) and release = trim(p_release) and created_at > now() - interval '1 hour') then
    return;
  end if;

  insert into public.website_observations (kind, name, value, rating, path, fingerprint, release, details, submission_hash)
  values (p_kind, trim(p_name), p_value, p_rating, p_path, trim(p_fingerprint), trim(p_release), coalesce(p_details, '{}'::jsonb), submission_hash_value);
end;
$$;

revoke all on function public.submit_website_observation(text,text,double precision,text,text,text,text,jsonb,uuid) from public;
grant execute on function public.submit_website_observation(text,text,double precision,text,text,text,text,jsonb,uuid) to anon, authenticated;

create or replace function public.purge_old_website_observations()
returns bigint language plpgsql security definer set search_path = public as $$
declare deleted_count bigint;
begin
  if auth.role() <> 'service_role' and not public.is_admin() then raise exception 'Admin access required'; end if;
  delete from public.website_observations where created_at < now() - interval '30 days';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
revoke all on function public.purge_old_website_observations() from public;
grant execute on function public.purge_old_website_observations() to authenticated;
