-- Restore the full legacy article bodies only when the database still holds
-- the short excerpt that was previously imported as the article content.
update public.news as n
set content = legacy.content
from (values
  ('/news/digital-advertising.jpg', E'Di era serba digital, cara brand berkomunikasi telah berubah jauh dibandingkan tahun-tahun sebelumnya. Videotron menjadi salah satu media pemasaran luar ruang yang menarik karena menampilkan konten dinamis, penuh warna, dan mudah menarik perhatian.\n\nVideotron memadukan gerak, warna, dan audio opsional sehingga dapat menangkap perhatian pejalan kaki maupun pengemudi dalam hitungan detik. Penempatan di pusat keramaian, persimpangan, atau area komersial meningkatkan frekuensi impresi secara signifikan.\n\nKonten iklan digital dapat diperbarui secara real-time tanpa biaya cetak ulang. Promo, produk baru, dan event musiman bisa langsung ditayangkan sehingga brand mampu merespons tren, situasi, cuaca, maupun kejadian lokal dengan cepat.\n\nDengan video, animasi, motion graphic, QR code, dan call-to-action, videotron membuka peluang storytelling visual yang kuat. Data tayangan dan interaksi juga membantu brand mengukur efektivitas kampanye serta mengoptimalkan konten dan jadwal tayang.\n\nVideotron bukan sekadar alat iklan, melainkan medium komunikasi visual yang membuat brand tampil modern, relevan, dan berdampak.'),
  ('/news/mandalika.png', E'Visitiga Media kembali membuktikan kredibilitasnya sebagai penyedia jasa LED dan event organizer terkemuka di Indonesia dengan dipercaya menjadi mitra teknologi tampilan visual untuk MotoGP Mandalika 2025, yang digelar pada 3–5 Oktober 2025 di Sirkuit Internasional Pertamina Mandalika, Lombok.\n\nVisitiga Media menyediakan lima set unit LED rental premium yang dirancang khusus untuk kebutuhan visual acara bertaraf internasional. Teknologi LED ini membantu penonton menikmati aksi balapan, waktu putaran, dan informasi teknis dengan kualitas visual terbaik.\n\nSalah satu highlight kontribusi Visitiga Media adalah desain LED khusus di garis start Sirkuit Mandalika. Area ini menjadi titik paling krusial saat balapan dimulai dan lampu-lampu start menyala.\n\nUntuk area podium, Visitiga Media menyediakan LED premium dengan resolusi tinggi P3.9, warna akurat dan konsisten, serta sistem audio-visual terintegrasi. Seluruhnya dirancang untuk mendukung momen penghargaan dan wawancara pemenang secara mewah dan profesional.\n\nKeterlibatan ini menambah portofolio Visitiga Media dalam industri event olahraga dan festival nasional, dengan solusi media terintegrasi dari perencanaan hingga maintenance.'),
  ('/news/digital-signage.png', E'Digital signage telah berevolusi jauh dari fungsi dasar menampilkan informasi. Di sektor hospitality, teknologi ini menjadi alat strategis yang menghubungkan tamu dengan layanan, pengalaman, dan citra merek secara real-time dan kontekstual.\n\nLayar interaktif di lobby dan entrance membantu tamu menemukan fasilitas tanpa harus bertanya ke pusat informasi. Penawaran F&B, promo, dan agenda acara yang ditampilkan secara visual juga dapat mendorong pembelian spontan.\n\nInformasi real-time seperti jadwal shuttle, cuaca, atau pengumuman penting membuat konsumen merasa lebih terlayani sekaligus mengurangi beban operasional staf.\n\nKonten visual berkualitas di area ramai seperti lobby, lift, dan lounge memperkuat identitas merek serta menciptakan kesan pertama yang konsisten. Integrasi dengan CRM atau PMS bahkan memungkinkan pesan yang lebih personal untuk tamu.\n\nVisitiga membantu brand menyatukan jaringan digital signage menjadi ekosistem yang mudah dikelola, dari penjadwalan konten hingga pengumpulan data engagement.'),
  ('/news/led-indoor-vs-outdoor.jpeg', E'Layar LED terlihat serupa dari jauh, tetapi komponennya dirancang untuk kondisi yang berbeda. Kecerahan, ketahanan terhadap cuaca, dan pixel pitch menentukan performa serta umur layar.\n\nLED indoor umumnya memiliki kecerahan 600–1.000 nits untuk ruang ber-AC dan pencahayaan terkontrol. LED outdoor membutuhkan 3.000–10.000+ nits agar tetap terbaca di bawah sinar matahari langsung.\n\nLED outdoor menggunakan enclosure tahan air dan debu, seperti IP65 atau IP66, pelapis anti-UV, ventilasi, serta sistem drainase. LED indoor tidak dirancang menghadapi perubahan suhu ekstrem, kelembapan, dan hujan.\n\nPixel pitch indoor biasanya lebih kecil, P1.25–P4, untuk jarak pandang dekat dan detail tinggi. Outdoor umumnya memakai P4–P16 karena jarak pandang lebih jauh. Memasang tipe yang salah dapat meningkatkan biaya energi, risiko kerusakan, dan downtime.\n\nPilih LED sesuai lokasi: indoor untuk ruang rapat atau studio, outdoor untuk billboard, facade, dan stadion, serta semi-outdoor dengan proteksi dan kecerahan menengah.'),
  ('/news/technology-visual.jpg', E'Di era digital, layar dan sistem audio-visual bukan lagi pelengkap, melainkan pengungkit hasil. Teknologi visual mengubah cara organisasi melayani tamu, menjual, mengajar, dan mengelola layanan.\n\nDalam hospitality, videowall, signage interaktif, dan Smart TV membantu menampilkan cerita merek, rekomendasi kuliner, hingga reservasi layanan. Hasilnya adalah pengalaman tamu yang lebih baik dan loyalitas yang meningkat.\n\nDi retail, display dinamis, mirror interaktif, dan digital pricing menghubungkan stok, promo, serta perilaku belanja sehingga kunjungan lebih lama, konversi meningkat, dan nilai transaksi rata-rata naik.\n\nDi pendidikan, layar interaktif, wireless presentation, dan lecture capture membuat kelas lebih eksploratif serta kolaboratif. Sementara di pemerintahan, pengumuman digital, kios mandiri, dan control room videowall membantu mempercepat layanan publik.\n\nSolusi yang baik selalu dimulai dari tujuan bisnis dan KPI, didukung konten relevan, integrasi CMS dengan CRM atau ERP, skalabilitas, aksesibilitas, dan keamanan.')
) as legacy(cover_image, content)
where n.cover_image = legacy.cover_image
  and n.content = n.excerpt;
