-- Anonymous, first-party page-view events for the admin overview.
-- No name, email, IP address, or other personal profile data is stored.
create table if not exists public.website_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  path text not null check (char_length(path) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists website_events_created_at_idx on public.website_events (created_at desc);
create index if not exists website_events_visitor_created_at_idx on public.website_events (visitor_id, created_at desc);
alter table public.website_events enable row level security;

drop policy if exists "Anyone can record page views" on public.website_events;
create policy "Anyone can record page views" on public.website_events for insert to anon, authenticated with check (true);
drop policy if exists "Admins view website events" on public.website_events;
create policy "Admins view website events" on public.website_events for select to authenticated using (public.is_admin());
drop policy if exists "Admins view contact messages" on public.contact_messages;
create policy "Admins view contact messages" on public.contact_messages for select to authenticated using (public.is_admin());

-- Push new events and contact leads to the dashboard without a manual refresh.
do $$ begin alter publication supabase_realtime add table public.website_events; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.contact_messages; exception when duplicate_object then null; end $$;
