import { useEffect, useState } from 'react';
import { LoaderCircle } from 'lucide-react';
import { deleteNews, listNews, saveNews } from '@/lib/adminApi';
import { ContentModal, InputField } from '@/components/admin/ContentModal';
import { Actions, Alert, Empty, Header } from '@/pages/admin/PortfoliosPage';
import type { NewsRecord } from '@/types/admin';

export default function NewsManagerPage() {
  const [items, setItems] = useState<NewsRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<NewsRecord | null>(null); const [creating, setCreating] = useState(false);
  const load = async () => { setLoading(true); try { setItems(await listNews()); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Berita tidak dapat dimuat.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (form: FormData) => { const date = String(form.get('published_at')); try { await saveNews({ title: String(form.get('title')).trim(), author: String(form.get('author')).trim(), category: String(form.get('category')).trim(), cover_image: String(form.get('cover_image')).trim(), excerpt: String(form.get('excerpt')).trim(), content: String(form.get('content')).trim(), published_at: date ? new Date(`${date}T00:00:00`).toISOString() : null }, editing?.id); setCreating(false); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Berita tidak dapat disimpan.'); } };
  const remove = async (id: string) => { if (!window.confirm('Hapus berita ini dari website?')) return; try { await deleteNews(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Berita tidak dapat dihapus.'); } };
  return <div className="mx-auto max-w-7xl"><Header title="Berita" description="Tambah, edit, atau hapus artikel yang tampil di halaman Berita." onAdd={() => setCreating(true)} />{error && <Alert text={error} />}<div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4">Artikel</th><th className="px-6 py-4">Penulis</th><th className="px-6 py-4">Publikasi</th><th className="px-6 py-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={4} className="px-6 py-14 text-center text-slate-500"><LoaderCircle className="mr-2 inline h-4 w-4 animate-spin" />Memuat berita…</td></tr> : items.length === 0 ? <Empty colSpan={4} text="Belum ada berita." /> : items.map((item) => <tr key={item.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><img src={item.cover_image} alt="" className="h-11 w-11 rounded-lg bg-slate-100 object-cover" /><div><p className="font-semibold text-slate-800">{item.title}</p><p className="max-w-64 truncate text-xs text-slate-500">{item.excerpt || item.content}</p></div></div></td><td className="px-6 py-4 text-slate-600">{item.author}</td><td className="px-6 py-4 text-slate-500">{item.published_at ? new Date(item.published_at).toLocaleDateString('id-ID') : 'Draft'}</td><Actions onEdit={() => setEditing(item)} onDelete={() => void remove(item.id)} /></tr>)}</tbody></table></div>{(creating || editing) && <ContentModal title={editing ? 'Edit berita' : 'Tambah berita'} onClose={() => { setCreating(false); setEditing(null); }} onSubmit={submit}><InputField label="Judul artikel" name="title" initial={editing?.title} className="sm:col-span-2" /><InputField label="Penulis" name="author" initial={editing?.author} /><InputField label="Kategori" name="category" initial={editing?.category} /><InputField label="Tanggal publikasi" name="published_at" type="date" required={false} initial={editing?.published_at?.slice(0, 10)} /><InputField label="URL cover" name="cover_image" initial={editing?.cover_image} className="sm:col-span-2" /><label className="sm:col-span-2 text-sm font-medium">Ringkasan<textarea name="excerpt" required defaultValue={editing?.excerpt ?? ''} rows={3} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 outline-none focus:border-orange-500" /></label><label className="sm:col-span-2 text-sm font-medium">Isi artikel<textarea name="content" required defaultValue={editing?.content ?? ''} rows={9} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 outline-none focus:border-orange-500" /></label></ContentModal>}</div>;
}
